[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "/.netlify/identity/verify"
  to = "/admin"
  status = 301

[[redirects]]
  from = "/.netlify/identity/confirm"
  to = "/admin"
  status = 301
