# src/admin/config.yml

backend:
  name: github
  repo: pppooolll/pppooolll-website
  branch: main
  base_url: https://gregarious-strudel-5d510f.netlify.app
  auth_endpoint: oauth

media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Type", name: "type", widget: "select", options: ["Built", "Unbuilt", "Documents"] }
      - { label: "Cover Image", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
